[package]
name = "typspec"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Gerson Gallo"]
license = "MIT"
description = "Structured specification document components for Typst"
repository = "https://github.com/ggallovalle/typspec"
compiler = "0.14"
