#import "../src/lib.typ": change, decision, requirement, scenario, task, task_group

#show: change.with(id: "refresh-skills", modifies: ("cli",))

= Proposal

== Motivation

The agent skills generated by `typspec init --tools` are out of date.
Since they were first written, several new features and conventions
have been added that the skills should reference:

- `typspec list` now shows file paths alongside names
- `typspec which <name>` locates files across specs/changes/archive
- `typspec/bibliographies/` is the canonical location for `.yaml` refs
- `@fuzzy-matching` and `@damlev` are the domain language for fuzzy lookups
- No more `bibliography` parameter on templates — use `#bibliography()`
  directly with path relative to project root via `--root`
- `typspec/` has a canonical structure: specs/, changes/, archive/, bibliographies/
- Config is always at `typspec/typspec.jsonc`

The skills should be regenerated with accurate, up-to-date instructions
that reference all of these.

== Scope

In scope:
- Update all 4 skill templates (propose, explore, apply, archive)
- Reference `typspec list --specs` and `typspec list` with path output
- Reference `typspec which` for file location
- Use `@fuzzy-matching` / `@damlev` where appropriate
- Reference canonical structure (`typspec/specs/`, `typspec/changes/`, etc.)
- Mention `#bibliography("typspec/bibliographies/...")` for citations

Out of scope:
- Adding new workflow skills (verify, sync, etc.)
- Interactive prompt support in skills
- Non-English skill templates

= Design

#decision(
  "Regenerate from updated Tera templates, keeping the same file structure",
  rationale: [
    The existing 4 templates (propose, explore, apply, archive) are the
    right set. Each needs updated content reflecting the current CLI
    capabilities. The Tera template system and tool registry remain
    unchanged — only the template text changes.
  ],
  alternatives: [
    - Add new skills: not needed, core 4 cover the workflow.
    - Refactor the template engine: overkill for a content update.
  ],
)

= Spec Deltas

== ADDED Requirements

#requirement("skill-updates-for-list", priority: "should", action: "added", modifies: "cli")[
  The skill templates SHALL reference `typspec list` and `typspec list --specs`
  as showing file paths, e.g., `module-api (typspec/specs/module-api.typ)`.

  #scenario("propose skill references list with paths",
    when: [skill is rendered],
    then: [it tells AI to use `typspec list --specs` to find specs with their paths],
  )
]

#requirement("skill-references-which", priority: "should", action: "added", modifies: "cli")[
  The skill templates SHALL reference `typspec which <name>` as the way to
  find the exact file path for a spec, change, or archived change.

  #scenario("archive skill references which",
    when: [skill is rendered],
    then: [it tells AI to use `typspec which <name>` to find archived changes],
  )
]

#requirement("skill-references-domain-language", priority: "should", action: "added", modifies: "cli")[
  The skill templates SHALL use `@fuzzy-matching` (from domain-language.yaml)
  when describing how typspec handles name lookup failures.

  #scenario("explore skill uses @fuzzy-matching",
    when: [skill describes name resolution],
    then: [references `@fuzzy-matching`],
  )
]

== MODIFIED Requirements

#requirement("skill-templates", action: "modified", modifies: "cli")[
  All four skill templates SHALL be updated to reflect current typspec
  behavior. Specific changes per template:

  *propose*: Reference `typspec list --specs` with paths, `typspec which`,
  canonical structure (`typspec/typspec.jsonc`, `typspec/specs/`, etc.),
  `#bibliography("typspec/bibliographies/...")` for citations. When no
  existing spec fits the change, prompt user to create a new spec with
  `typspec new spec <name>`.

  *explore*: Mention `typspec which` for finding files, `@fuzzy-matching`
  for name resolution, canonical directory layout.

  *apply*: Reference `typspec list` with paths, `typspec status` for
  task descriptions and paths.

  *archive*: Mention `typspec which` for finding archived changes,
  `typspec/bibliographies/` for references.
]

= Tasks

#task_group("1. Propose Template", (
  task([Update propose.md: reference list --specs with paths, which, canonical structure, \#bibliography()], done: false, labels: ("cli",)),
))

#task_group("2. Explore Template", (
  task([Update explore.md: reference which, \@fuzzy-matching, canonical dirs], done: false, labels: ("cli",)),
))

#task_group("3. Apply Template", (
  task([Update apply.md: reference list with paths, status for paths], done: false, labels: ("cli",)),
))

#task_group("4. Archive Template", (
  task([Update archive.md: reference which for archived changes, bibliographies/], done: false, labels: ("cli",)),
))

#task_group("5. Verify", (
  task([Generate skills with `typspec init --tools opencode`, verify content], done: false, labels: ("tests",)),
  task([Spot-check each skill for accuracy against current CLI behavior], done: false, labels: ("tests",)),
))
