#import "../src/lib.typ": spec, requirement, scenario, decision

#show: spec.with(title: "AI Agent Skills")

= AI Agent Skills Specification

This document specifies the AI agent skill files generated by
`typspec init --tools <tool>`.

= Skill Generation

#requirement("init-tools-flag", priority: "shall")[
  The `typspec init` command SHALL accept a `--tools` flag that accepts
  a comma-separated list of AI tool IDs. Supported tool IDs: `claude`,
  `codex`, `opencode`.

  Passing `--tools all` SHALL select all supported tools.
  Passing `--tools none` SHALL skip skill generation.

  #scenario("tools claude",
    when: [`typspec init --tools claude`],
    then: [skills generated in `.claude/skills/`],
  )

  #scenario("tools opencode",
    when: [`typspec init --tools opencode`],
    then: [skills generated in `.agents/skills/`],
  )

  #scenario("tools all",
    when: [`typspec init --tools all`],
    then: [skills generated for all tools],
  )
]

== Skill File Format

#requirement("skill-yaml-frontmatter", priority: "shall")[
  Each generated `SKILL.md` SHALL start with YAML frontmatter containing:

  ```yaml
  ---
  name: typspec-<workflow>
  description: <thorough description>
  license: MIT
  compatibility: Requires typspec CLI.
  metadata:
    author: typspec
    version: "0.1.0"
    generatedBy: "0.1.0"
  ---
  ```

  #scenario("frontmatter present",
    when: [skill is generated],
    then: [name, description, license, compatibility, and metadata fields exist],
  )
]

== Required Skills

#requirement("skill-propose", priority: "shall")[
  The `typspec-propose` skill SHALL guide an AI through creating a change
  document. It SHALL reference:
  - `typspec list` and `typspec list --specs` for discovering existing files
  - `typspec new change <name>` for creating the change file
  - `typspec validate typspec/changes/<name>.typ` for verification
  - The canonical structure: `typspec/typspec.jsonc`, `typspec/specs/`

  For bibliographies, the skill SHALL use a generic placeholder:
  `#bibliography("typspec/bibliographies/<your-file>.yaml")` — not a
  hardcoded file name.

  When the AI cannot identify an existing spec that the change modifies,
  it SHALL explain to the user that the change's scope doesn't align with
  any existing spec and prompt them to create a new one via
  `typspec new spec <name>`.

  #scenario("propose creates change",
    when: [AI follows the skill],
    then: [a `.typ` file is created in `typspec/changes/` with all sections],
  )

  #scenario("no matching spec prompts new spec",
    given: [change doesn't logically fit any existing spec],
    when: [AI evaluates modifies targets],
    then: [
      AI explains the reasoning to the user,
      prompts `typspec new spec <name>` to create it,
      change's `modifies` references the new spec,
    ],
  )
]

#requirement("skill-explore", priority: "shall")[
  The `typspec-explore` skill SHALL guide an AI through exploratory
  thinking. It SHALL reference:
  - `typspec list` and `typspec list --specs` to check what exists
  - `typspec which <name>` to find file locations
  - The canonical directory structure

  It SHALL emphasize: *explore mode is for thinking, not implementing*.

  The skill SHALL NOT reference `@fuzzy-matching` or any repo-specific
  domain language. The CLI handles name resolution transparently — the
  AI only needs to know `typspec which <name>`.

  #scenario("explore investigates",
    when: [AI enters explore mode],
    then: [it checks existing specs/changes before proposing anything],
  )
]

#requirement("skill-apply", priority: "shall")[
  The `typspec-apply` skill SHALL guide an AI through implementing tasks
  from a change document. It SHALL reference:
  - `typspec list` showing paths to find active changes
  - `typspec status <name>` to see task descriptions and completion
  - `typspec status <name> --json` for machine-readable metadata
  - `typspec validate typspec/changes/<name>.typ` after each task

  #scenario("apply implements tasks",
    when: [AI follows the skill],
    then: [it reads change file, implements tasks, marks done: true],
  )
]

#requirement("skill-archive", priority: "shall")[
  The `typspec-archive` skill SHALL guide an AI through archiving a
  completed change. It SHALL reference:
  - `typspec status <name>` to verify task completion
  - `typspec archive <name>` to merge deltas and move to archive
  - `typspec validate typspec/specs/<spec>.typ` to verify modified specs
  - `typspec which <name>` to find archived changes later

  It SHALL NOT include a "Bibliography references" section — archive
  is not the workflow for introducing bibliography dependencies.

  #scenario("archive completes change",
    when: [AI follows the skill],
    then: [deltas merged, change moved to archive, specs verified],
  )
]

= Tool Directory Mapping

#requirement("tool-directories", priority: "shall")[
  Skills are written to tool-specific directories:

  | Tool      | Skills dir          |
  |-----------|---------------------|
  | `claude`  | `.claude/skills/`   |
  | `codex`   | `.agents/skills/`   |
  | `opencode`| `.agents/skills/`   |

  The directory SHALL be created if it does not exist. Existing skill
  files SHALL be overwritten.

  #scenario("claude skills dir",
    when: [`--tools claude`],
    then: [`.claude/skills/typspec-*/SKILL.md` created],
  )

  #scenario("opencode skills dir",
    when: [`--tools opencode`],
    then: [`.agents/skills/typspec-*/SKILL.md` created],
  )
]

#bibliography("../bibliographies/domain-language.yaml", style: "iso-690-numeric")
