#import "../src/lib.typ": spec, requirement, scenario
#import "../links.typ"
#import "../glossary.typ"

#show: glossary.glossary
#show: spec.with(title: "AI Agent Skills")

= AI Agent Skills Specification

This document specifies the content and structure of AI agent skill files
generated by `typspec init --tools <tool>`.

== Skill File Format

#requirement("skill-yaml-frontmatter", priority: "shall")[
  Each generated `SKILL.md` SHALL start with YAML frontmatter containing:

  ```yaml
  ---
  name: typspec-<workflow>
  description: <thorough description>
  license: MIT
  compatibility: Requires typspec CLI.
  metadata:
    author: typspec
    version: "0.1.0"
    generatedBy: "0.1.0"
  ---
  ```

  #scenario("frontmatter present",
    when: [skill is generated],
    then: [name, description, license, compatibility, and metadata fields exist],
  )
]

== Required Skills

=== typspec-propose

#requirement("skill-propose", priority: "shall")[
  The `typspec-propose` skill SHALL guide an AI through creating a change
  document. It SHALL reference:
  - `typspec list` and `typspec list --specs` for discovering existing files
    with their paths
  - `typspec which <name>` for finding file locations
  - `typspec new change <name>` for creating the change file
  - `typspec validate typspec/changes/<name>.typ` for verification
  - The canonical structure: `typspec/typspec.jsonc`, `typspec/specs/`

  When no existing spec fits the change, SHALL prompt user to create a new
  spec with `typspec new spec <name>`.

  #scenario("bibliography ref is generic",
    when: [propose skill references bibliography],
    then: [uses `<your-file>.yaml` placeholder, not a specific file],
  )
]

=== typspec-explore

#requirement("skill-explore", priority: "shall")[
  The `typspec-explore` skill SHALL guide an AI through exploratory
  thinking. It SHALL reference:
  - `typspec list` and `typspec list --specs` to check what exists
  - `typspec which <name>` to find file locations
  - The canonical directory structure

  It SHALL emphasize: *explore mode is for thinking, not implementing*.

]

=== typspec-apply

#requirement("skill-apply", priority: "shall")[
  The `typspec-apply` skill SHALL guide an AI through implementing tasks
  from a change document. It SHALL reference:
  - `typspec list` showing paths to find active changes
  - `typspec status <name>` to see task descriptions and completion
  - `typspec status <name> --json` for machine-readable metadata
  - `typspec validate typspec/changes/<name>.typ` after each task

  #scenario("apply implements tasks",
    when: [AI follows the skill],
    then: [it reads change file, implements tasks, marks done: true],
  )
]

=== typspec-archive

#requirement("skill-archive", priority: "shall")[
  The `typspec-archive` skill SHALL guide an AI through archiving a
  completed change. It SHALL reference:
  - `typspec status <name>` to verify task completion
  - `typspec archive <name>` to merge deltas and move to archive
  - `typspec validate typspec/specs/<spec>.typ` to verify modified specs
  - `typspec which <name>` to find archived changes later

  It SHALL NOT include a "Bibliography references" section — archive
  is not the workflow for introducing bibliography dependencies.

  #scenario("no bibliography section in archive",
    when: [archive skill file is examined],
    then: [no Bibliography references section exists],
  )
]

== Template Requirements

#requirement("skill-templates", priority: "shall")[
  All four skill templates SHALL reference:
  - `typspec list` showing file paths
  - `typspec which <name>` for finding file locations
  - The canonical directory layout (`typspec/typspec.jsonc`, `typspec/specs/`)

  #scenario("propose references list with paths",
    when: [propose skill is rendered],
    then: [it tells AI to use `typspec list --specs` with paths],
  )

  #scenario("archive skill references which",
    when: [archive skill is rendered],
    then: [it tells AI to use `typspec which` to find archived changes],
  )
]

#requirement("mermaid-diagrams", priority: "shall")[
  The `typspec-propose` and `typspec-explore` skill templates SHALL
  prefer Mermaid diagram syntax over ASCII art for structured diagrams
  (flowcharts, sequence diagrams, state machines).

  ASCII art is acceptable when the concept doesn't map to a standard
  Mermaid diagram type.

  #scenario("propose uses mermaid",
    given: [the propose skill describes a workflow],
    when: [rendering a flow],
    then: [uses ```mermaid flowchart LR ...``` instead of ASCII arrows],
  )

  #scenario("fallback to ascii",
    given: [a concept with no Mermaid equivalent],
    when: [rendering],
    then: [uses ASCII art as fallback],
  )
]

== Sourcing

#requirement("single-source-skills", priority: "shall")[
  Skill templates SHALL be sourced from the canonical `skills/typspec/`
  directory only. The `crates/cli/templates/` directory and `tera`
  dependency SHALL be removed.

  At compile time, each `SKILL.md` file from `skills/typspec/` SHALL be
  embedded via `include_str!()`. The YAML `metadata.generatedBy` field
  SHALL contain a `VERSION` marker that gets replaced with the crate
  version at generation time.

  #scenario("tera removed",
    when: [crate compiles],
    then: [no `tera` dependency, no `templates/` directory],
  )

  #scenario("skills embedded",
    when: [CLI runs `init --tools`],
    then: [skills written from embedded source, match `skills/` canonical forms],
  )

  #scenario("version injected",
    when: [skill is generated],
    then: [`metadata.generatedBy` matches the CLI version, not hardcoded],
  )
]

